#!/bin/bash

# We only want to run the script if the board has RGB capability
if ! knulli-board-capability "rgb"; then
    exit 1
fi

case "$1" in
  start)
  # Code in here will only be executed on start.
    #TODO cd into hh-prime-rgb directory
    nohup python rgb_daemon.py &>/dev/null &
    ;;
  stop)
    # Code in here will only be executed on shutdown.
    /usr/bin/knulli-rgb-led-daemon stop
    ;;
  *)
    # Code in here will be executed in all other conditions.
    echo "Usage: $0 {start|stop}"
    ;;
esac

exit $?
