#!/bin/sh


if test -f /userdata/system/.asound.state; then
    echo "~/.asound.state already exists. This script needs to be run only once per device. Exiting"
    exit 0
fi

try_headphone_volume() {
    N=20
    while test "${N}" -gt 0
    do
        echo "retry applying audio (${N})" >&2
        value=$(amixer sget "Headphone" | sed -n "s/  Mono: \([0-9]*\) .*/\1/p")
        echo "Value: $value"
        if [ "$value" -eq 1 ]
        then
            return 0
        fi
	    amixer set 'Headphone' 1
        sleep 3
	    N=$((N-1))
    done
    return 1
}

if test "$1" = "start"
then
    sleep 1
    try_headphone_volume
fi


