#!/bin/bash

BOARD="$(cat /boot/boot/batocera.board)"
if [ "$BOARD" != "trimui-brick" ] && [ "$BOARD" != "trimui-smart-pro" ]; then
    exit 1
fi

# Wait for emulationstation to be ready so this runs after everything else has initialized
for i in {1..20}; do
    [ -f /tmp/emulationstation.ready ] && break
    sleep 0.5
done

case "$1" in
    start)
        SWITCH_STATE=$(cat /sys/class/gpio/gpio243/value)
        TOGGLE_SWITCH="/usr/bin/toggle-switch"

        if [ "$SWITCH_STATE" -eq 1 ]; then
            "$TOGGLE_SWITCH" enable
        else
            "$TOGGLE_SWITCH" disable
        fi
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac

exit 0
