#!/bin/bash

log="/tmp/resize.log"

# only at start
test "$1" != "start" && exit 0

mount -o rw,remount /boot
# true if triggers are not available or not set to do so
if [ ! -f /boot/boot/autoresize ]
then
    exit 0
fi

# --- BEGIN RESIZE ---
# remove the trigger
rm -f /boot/boot/autoresize
DISK=/dev/mmcblk0
PART=/dev/mmcblk0p3
PARTNUM=3

cd /root
umount /boot

sgdisk -e ${DISK} >> "$log"
parted -s -m ${DISK} align-check opt ${PARTNUM} >> "$log"
parted -s -m ${DISK} resizepart ${PARTNUM} 100% >> "$log"
partprobe ${DISK} >> "$log"

e2fsck -f -p ${PART} >> "$log"
resize2fs ${PART}  >> "$log"

sleep 1

partprobe ${DISK} >> "$log"

echo -e “d\n3\nn\p\n3\n7356416\ny\nt\n3\n7\n\nw\n” | fdisk {$DISK}

partprobe ${DISK} >> "$log"

#mkfs.vfat -n SHARE ${PART}
mkfs.exfat -n SHARE ${PART} >> "$log"

partprobe ${DISK} >> "$log"

#first time, so we reboot
#reboot

exit 0


